### ISSUE TITLE
Prompt doesn't show on other navigation events

### ISSUE THREAD

**Issue by salali** [cgkineo/adapt-pageIncompletePrompt#1]
Currently the prompt only shows on this event: "navigation:backButton"

The extension should listen to any type of navigation away from a page.

**Comment by tomgreenfield** [comment]
I've added a handler for the navigation:menuButton event in 70ceef8606135cc54b10fda076f877d8fe4761a7.

Since the routing for this event is handled in the Kineo fork, I've been able to add the _canNavigate check in https://github.com/cgkineo/adapt-framework-kineoFork/commit/25b50bd21ccc3092d8184bc0ce75efa52d8bdfdb.

**Comment by tomgreenfield** [comment]
Looks like this work has been redone straight into master in https://github.com/cgkineo/adapt-pageIncompletePrompt/commit/aeb6f80aff0435eb9ba431ec373c7df02fed243c so will close the issue branch.

We'll need to tweak this at some point to work instead with the *navigation:homeButton* event used in v2 of the framework.

**Comment by moloko** [comment]
Pretty sure this is now dealt with - certainly I now get the prompt when navigation via `Backbone.history.navigate()`
If there are any further issues like this a new ticket can be raised
