### ISSUE TITLE
Breaks box menu View button on re-visit

### ISSUE THREAD

**Issue by mldaq** [cgkineo/adapt-pageIncompletePrompt#13]
This extension was working great up until about 2 weeks ago when I did an upgrade of my the framework. I was not sure what was going on until I ran a few test. My course worked fine without this extension, but when I added the extension the box menu "View" button is disabled upon a re-visit to the main menu page. Steps below:

1. Open course
2. Select "View" button > Enter page
3. Click back or home button
4. Select "View" > **nothing happens**

**Comment by moloko** [comment]
Looks like the Adapt 2.1.3 release broke this, specifically https://github.com/adaptlearning/adapt_framework/pull/1583

When I revert those changes it all works. When I reapply them, it breaks again - PIP doesn't appear when navigating away from an incomplete page and you then can't navigate to another page either by using the menu buttons or by changing `location.hash`

@oliverfoster any chance you could have a look tomorrow? this is going to cause us a lot of issues otherwise...

**Comment by mldaq** [comment]
FYI - we are using this in many of our courses. If the designer/developer re-applies the theme they can no longer navigate the course properly. My instructions for now is to remove the extension. 

@oliverfoster @moloko

**Comment by moloko** [comment]
@mldaq if you're using the framework you could revert your router.js back to [this version](https://raw.githubusercontent.com/adaptlearning/adapt_framework/8e98a06d172a96e1ce34d089ec7284cb30c37a38/src/core/js/router.js) as a temporary workaround?

**Comment by mldaq** [comment]
I had to publish a course this morning and ended up taking it out. We are mostly using the authoring environment.

Thank you!

Best Regards,

Mark D'Aquin
Learning Solutions Architect, Learning Content Strategy and Learner Experience
SAP Learning
SAP SE USA
M: 214-535-9047

[cid:image001.png@01D3008A.C01AB920]

**Comment by oliverfoster** [comment]
Yup, bug was with the pr I did as identified by @moloko fixed in pr https://github.com/adaptlearning/adapt_framework/issues/1582

**Comment by moloko** [comment]
hi @mldaq this should be fixed in [v2.0.5](https://github.com/cgkineo/adapt-pageIncompletePrompt/releases/tag/v2.0.5) - certainly works fine now for me anyway. Note that this updated version requires v2.2.0 (or better) of the Adapt Framework.
